#!/usr/bin/env bash
#
#   hello-server-test - Confirm "hello" server is returning correct data
#
set -Eeuo pipefail
trap '
    ec=$?
    echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO"
    echo 1>&2 "    file=$0"
    echo 1>&2 "    cmd=$BASH_COMMAND"
    exit $ec;
' ERR

echo '===== test-hello-server'
expected='Hello.'
actual=$(curl --silent --show-error http://127.0.0.1:9999/hello)
[[ $expected == $actual ]] || {
    echo 1>&2 "FAILED: expected='$expected' actual='$actual'"
    exit 1
}
echo '----- OK'
