#!/usr/bin/env bash
set -Eeuo pipefail
trap '
    ec=$?
    echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO"
    echo 1>&2 "    file=$0"
    echo 1>&2 "    cmd=$BASH_COMMAND"
    exit $ec;
' ERR

export PROJDIR=$(command cd "$(dirname "$0")" && pwd -P)
cd "$PROJDIR"

echo '===== test-hello-server'

source ../docker/rustup-env
cargo run -q & server_pid=$!; sleep 0.5    # give it startup time

expected='Hello.'
actual=$(curl --silent --show-error http://127.0.0.1:80/hello)
#   The server is killed on exit anyway, but this collects the zombie.
kill $server_pid; wait

[[ $expected == $actual ]] || {
    echo 1>&2 "FAILED: expected='$expected' actual='$actual'"
    exit 1
}
echo '----- OK'
