#!/usr/bin/env bash
set -Eeuo pipefail
trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO"; exit $ec' ERR

export PROJDIR=$(command cd "$(dirname "$0")/.." && pwd -P)
mkdir -p "$PROJDIR"/.build/package
command cd "$PROJDIR"/.build/package

pkgname=webhello-0.0.1-1.$(dpkg --print-architecture)

mkdir -p $pkgname/usr/bin/
cp ../cargo/webhello/debug/webhello $pkgname/usr/bin
chmod 0755 $pkgname/usr/bin/webhello

mkdir -p $pkgname/etc/systemd/system/
cp ../../package/webhello.service $pkgname/etc/systemd/system/
chmod 0644 $pkgname/etc/systemd/system/webhello.service

mkdir -p $pkgname/DEBIAN/
cp ../../package/DEB.control $pkgname/DEBIAN/control
chmod 0644 $pkgname/DEBIAN/control

dpkg-deb --build --root-owner-group $pkgname
